### ISSUE TITLE
position of scrollbar is not correct on production build

### ISSUE THREAD

**Issue by HuyTruongSharecare** [goldenyz/react-perfect-scrollbar#51]
I have an issue with scrollbar position. When I run my app on production build, scrollbar is showed at the left of my list. I tried to check the style of ps__rail-y element and found that style of left is 0. But on development mode that work ok. Pls help me to resolve this issue

**Comment by goldenyz** [comment]
Can you show me your code?

**Comment by HuyTruongSharecare** [comment]
Hi @goldenyz 
This is my code
![image](https://user-images.githubusercontent.com/43661674/47960450-124e3480-e02f-11e8-85db-99120aacb0c6.png)
and this is on my web 
![image](https://user-images.githubusercontent.com/43661674/47961085-5264e580-e036-11e8-8749-7420f8fdb362.png)

I using create-react-app to build my project. Thanks

**Comment by emersonbottero** [comment]
I'm having the same problem did you found a workaround?

**Comment by MyGithub-Ljc** [comment]
i have this problem on development mode , Do you have a solution？

**Comment by goldenyz** [comment]
Could you repro it on codesandbox.io to help me find out what happens?

**Comment by MyGithub-Ljc** [comment]
@goldenyz  在create-react-app 1.X的脚手架上是OK的，在2.X的下面就会出现这个问题，开发环境下滚动条位置在左侧，生产环境下是正常的。

**Comment by goldenyz** [comment]
@MyGithub-Ljc 创建个github仓库，我拷贝下来试一下？

**Comment by MyGithub-Ljc** [comment]
@goldenyz  https://github.com/MyGithub-Ljc/test-of-scrollbar.git

**Comment by goldenyz** [comment]
It would be a issue caused by the execution order of the css files.
When in development mode, the css file is referenced by `blob:` style url, which cause the css execution later then js.
You can make a workaround in `config/webpack.config.js` line 81 to:
```js
options: Object.assign(
  {},
  cssOptions,
  {
    sourceMap: false, // disable the css-loader's sourcemap, which makes the style inlined
  }
),
```
![image](https://user-images.githubusercontent.com/8434711/53724799-a927e200-3ea5-11e9-805d-b8b06281557b.png)

@HuyTruongSharecare @emersonbottero Your issue may be related to the css file execution order, too.

**Comment by MyGithub-Ljc** [comment]
谢谢 lz 的热心解答，同时也解决了我另一个疑问。

**Comment by hungnguyen1995** [comment]
please fix it :(
